### ISSUE TITLE
'number is not a function' error when trying to log in

### ISSUE THREAD

**Issue by dancancro** [CleverStack/node-seed#100]
This is happening when I click the Login button.

    GET /user/current 404 11ms - 2b
    OPTIONS /user/login 204 2ms
    Mongoose: users.findOne({ email: 'a@a.com', password: '86f7e437faa5a7fce15d1ddcb9eaeaea377667b8', confirmed: true, active: true }) { fields: undefined, safe: undefined }
    Mongoose: users.update({ _id: ObjectId("53cfd22b1766a00541000001") }) { '$set': { accessedAt: new Date("Wed, 23 Jul 2014 16:10:25 GMT"), updatedAt: new Date("Wed, 23 Jul 2014 16:10:25 GMT") } } {}

    /Users/Dan/work/clever-3/backend/lib/classes/Model.js:600
                            callback( null );
                            ^
    TypeError: number is not a function
        at updateObject (/Users/Dan/work/clever-3/backend/lib/classes/Model.js:600:25)
        at fn (/Users/Dan/work/clever-3/backend/node_modules/async/lib/async.js:641:34)
        at Object._onImmediate (/Users/Dan/work/clever-3/backend/node_modules/async/lib/async.js:557:34)
        at processImmediate [as _immediateCallback] (timers.js:336:15)
    Mongoose: users.ensureIndex({ username: 1 }) { safe: undefined, background: true, unique: true }
    Mongoose: users.ensureIndex({ email: 1 }) { safe: undefined, background: true, unique: true }
    Mongoose: users.findOne({ email: 'a@a.com', password: '86f7e437faa5a7fce15d1ddcb9eaeaea377667b8', confirmed: true, active: true }) { fields: undefined, safe: undefined }
    Mongoose: users.update({ _id: ObjectId("53cfd22b1766a00541000001") }) { '$set': { accessedAt: new Date("Wed, 23 Jul 2014 16:10:26 GMT"), updatedAt: new Date("Wed, 23 Jul 2014 16:10:26 GMT") } } {}

**Comment by pilsy** [comment]
This has been fixed in the latest release of clever-odm
